Repository timvideos/litex-buildenv, pull requests merged in 2018-10, with the labels that each got.

#74 Final Touches On TinyFPGA Platform
  targets/tinyfpga_bx/base.py
Labels: firmware-softcpu, hdmi2***, level-firmware

#81 Add ICE40HX8K-B-EVN Platform
  .travis.yml
  platforms/ice40_hx8k_b_evn.py
  targets/ice40_hx8k_b_evn/Makefile.mk
  targets/ice40_hx8k_b_evn/base.py
Labels: hdmi2***, level-infrastructure

#88 LiteX readme
  README.md
Labels: level-docs

#89 Firmware CR-NL
  firmware/ci.c
Labels: firmware-softcpu, level-firmware

#90 ICE40UP5K-B-EVN Support
  .travis.yml
  gateware/up5kspram.py
  platforms/ice40_up5k_b_evn.py
  targets/ice40_up5k_b_evn/Makefile.mk
  targets/ice40_up5k_b_evn/base.py
  targets/ice40_up5k_b_evn/bridge.py
Labels: firmware-fpga, hdmi2***, level-firmware, level-infrastructure

#87 scripts: Use GCC 8.2.0 on or1k too.
  scripts/settings.sh
Labels: level-infrastructure

#85 Fixes for Linux build
  scripts/build-linux.sh
Labels: level-infrastructure

#95 platforms: Add icebreaker platform with base target. Micropython boots.
  .travis.yml
  platforms/icebreaker.py
  targets/icebreaker/Makefile.mk
  targets/icebreaker/base.py
Labels: hdmi2***, level-infrastructure
