Repository timvideos/litex-buildenv, pull requests merged in 2019-07, with the labels that each got.

#158 scripts: Use older version of conda.
  scripts/download-env.sh
  scripts/settings.sh
Labels: level-infrastructure

#160 scripts: switch to portable Renode release
  scripts/build-renode.sh
Labels: level-infrastructure

#147 travis: test zephyr script and save built binary
  .travis.yml
  .travis/build.sh
  scripts/download-env.sh
  scripts/enter-env.sh
  scripts/settings.sh
Labels: level-infrastructure

#154 Renode boot from flash
  scripts/build-renode.sh
  scripts/generate-renode-scripts.py
Labels: level-infrastructure

#156 Update CPU=or1k to CPU=mor1kx for upstream change.
  .travis.yml
  .travis/run.inc.sh
  Makefile
  scripts/build-linux.sh
  scripts/build-qemu.sh
  scripts/download-env.sh
  scripts/enter-env.sh
Labels: level-infrastructure

#163 Cleanup failing targets
  .travis.yml
  platforms/netv2.py
  targets/arty/bridge_net.py
  targets/arty/ddr3.py
  targets/mimasv2/memtest.py
  targets/netv2/Makefile.mk
  targets/netv2/TODO.md
  targets/netv2/base.py
  targets/netv2/bridge_pcie.py
  targets/netv2/bridge_uart.py
  targets/netv2/pcie.py
  targets/netv2/video.py
  targets/nexys_video/bridge_net.py
  targets/nexys_video/ddr3.py
  targets/nexys_video/etherbone.py
  targets/opsis/memtest.py
  targets/opsis/video_out_debug.py
Labels: board-arty, board-mimasv2, board-netv2, board-opsis, boards-artix7, boards-spartan6, hdmi2***, level-docs, level-infrastructure

#162 Small scripts cleanup
  Makefile
  scripts/download-env.sh
  scripts/enter-env.sh
Labels: level-infrastructure

#165 scripts: fix running portable Renode
  scripts/build-renode.sh
Labels: level-infrastructure

#166 scripts: Add vexriscv as default CPU.
  scripts/download-env.sh
  scripts/enter-env.sh
Labels: level-infrastructure

#164 platform/icebreaker: port rgb led driver from fomu
  gateware/ice40.py
  platforms/icebreaker.py
  targets/ice40_up5k_b_evn/base.py
  targets/icebreaker/base.py
  targets/upduino_v1/base.py
Labels: firmware-fpga, hdmi2***, level-firmware

#168 scripts : fix download-env/enter-env platform detection
  scripts/download-env.sh
  scripts/enter-env.sh
Labels: level-infrastructure

#169 More RISC-V builds on travis
  .travis.yml
Labels: level-infrastructure

#176 Fix endianness
  firmware/uip/contiki-conf.h
  targets/arty/net.py
  targets/atlys/net.py
  targets/mimas_a7/net.py
  targets/nexys_video/net.py
  targets/opsis/net.py
  targets/sim/net.py
Labels: board-arty, board-atlys, board-opsis, board-sim, boards-artix7, boards-spartan6, firmware-softcpu, hdmi2ethernet, level-firmware

#177 scripts: Always update conda to pinned version.
  scripts/download-env.sh
Labels: level-infrastructure

#183 Exclude glusterfs from qemu build
  scripts/build-qemu.sh
Labels: level-infrastructure

#185 scripts: More aggressive tun creation.
  scripts/build-common.sh
Labels: level-infrastructure

#178 scripts: Update toolchain.
  scripts/settings.sh
Labels: level-infrastructure

#174 Better vexriscv linux support
  .travis.yml
  Makefile
  scripts/build-linux.sh
  targets/arty/base.py
  targets/opsis/base.py
Labels: board-arty, board-opsis, boards-artix7, boards-spartan6, firmware-softcpu, hdmi2***, hdmi2ethernet, level-firmware, level-infrastructure
