Repository timvideos/litex-buildenv, pull requests merged in 2019-11, with the labels that each got.

#221 Improvements to local git submodule script.
  .travis/add-local-submodule-inner.sh
  .travis/add-local-submodule.sh
  .travis/add-local-submodules.sh
  .travis/fixup-git.sh
Labels: level-infrastructure

#220 zephyr: Add missing `packaging` dependency
  .travis.yml
  scripts/download-env.sh
  scripts/enter-env.sh
Labels: level-infrastructure

#203 micropython: allow to skip building image
  scripts/build-micropython.sh
Labels: level-infrastructure

#204 Allow to pass additional arguments to Renode
  scripts/build-renode.sh
Labels: level-infrastructure

#212 Use Renode from Conda
  scripts/build-linux.sh
  scripts/build-renode.sh
  scripts/download-env.sh
  scripts/enter-env.sh
Labels: level-infrastructure

#233 [FIX] scripts: Use python package for MimasV2Config
  scripts/download-env.sh
  scripts/enter-env.sh
  targets/mimasv2/Makefile.mk
Labels: board-mimasv2, boards-spartan6, level-infrastructure

#232 Renode fixes
  scripts/build-linux.sh
  scripts/build-renode.sh
  targets/arty/base.py
  targets/atlys/base.py
  targets/ice40_hx8k_b_evn/base.py
  targets/ice40_up5k_b_evn/base.py
  targets/icebreaker/base.py
  targets/icefun/base.py
  targets/mimasv2/base.py
  targets/minispartan6/base.py
  targets/opsis/base.py
  targets/pipistrello/base.py
  targets/sim/base.py
  targets/tinyfpga_bx/base.py
  targets/upduino_v1/base.py
Labels: board-arty, board-atlys, board-ice40_hx8k_b_env, board-mimasv2, board-minispartan6, board-opsis, board-pipistrello, board-sim, board-tinyfpga_bx, boards-artix7, boards-ice40, boards-spartan6, hdmi2***, level-infrastructure

#223 platforms: add pano logic g2 platform
  .travis.yml
  platforms/pano_logic_g2.py
  targets/pano_logic_g2/Makefile.mk
  targets/pano_logic_g2/base.py
Labels: hdmi2***, level-infrastructure

#230 scripts/build-linux.sh: add option to build rootfs and devicetree from scratch
  .gitignore
  make.py
  scripts/build-linux.sh
Labels: level-infrastructure

#246 targets: arty: add tf target
  targets/arty/tf.py
Labels: board-arty, boards-artix7
