Repository timvideos/litex-buildenv, pull requests merged in 2020-07, with the labels that each got.

#338 Zephyr Arty no DDR
  firmware/pattern.c
  targets/arty/zephyr_no_ddr.py
Labels: board-arty, boards-artix7, firmware-softcpu, level-firmware

#473 targets: Fix loading gateware
  load.py
  targets/arty/Makefile.mk
  targets/basys3/Makefile.mk
  targets/cmod_a7/Makefile.mk
  targets/common/openocd.mk
  targets/mimas_a7/Makefile.mk
  targets/neso/Makefile.mk
  targets/waxwing/Makefile.mk
Labels: board-arty, board-basys3, board-cmod_a7, board-neso, board-waxwing, boards-all, boards-artix7, boards-spartan6

#480 Set Xilinx gateware toolchain location
  .travis/download-xilinx.sh
  scripts/download-env.sh
  scripts/enter-env.sh
Labels: level-infrastructure

#450 linux: unify linux source
  Makefile
  configs/linux-rootfs/README
  configs/linux-rootfs/buildroot_mor1kx.config
  configs/linux-rootfs/buildroot_vexriscv.config
  configs/linux-rootfs/rootfs_overlay/etc/profile
  scripts/build-linux.sh
  tests/renode/Firmware-linux.robot
Labels: level-infrastructure

#484 download-env: Fix the installation of some python modules
  scripts/download-env.sh
Labels: level-infrastructure
