Repository timvideos/litex-buildenv, pull requests merged in 2020-04, with the labels that each got.

#385 micropython: use fupy/micropython fork
  scripts/build-micropython.sh
Labels: level-infrastructure

#396 Fix Arty TF target
  targets/arty/tf.py
Labels: board-arty, boards-artix7

#397 Add emulator_ram to fix CPU_VARIANT=linux build for pano_logic_g2.
  targets/pano_logic_g2/base.py
Labels: hdmi2***

#410 Panologic: Added SPI flash support. Successfully boots Linux from flash.
  platforms/pano_logic_g2.py
  targets/pano_logic_g2/base.py
Labels: hdmi2***
